version: "3.9"

services:
  mysql80:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
    restart: always
    ports:
      - 3306:3306
    # volumes:
    # - ~/docker/data/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
