version: "3.9"

services:
  mysql57:
    image: biarms/mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    # volumes:
    # - ~/docker/data/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
